<?php
namespace kaikaige\job;

use kaikaige\job\components\JobClient;
use Yii;
use yii\helpers\Url;
use yii\httpclient\Client;

class Module extends \yii\base\Module
{
    /**
     * @var string
     */
    public $addr;

    /**
     * @var JobClient
     */
    public $client;

    public $controllerNamespace = 'kaikaige\job\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->defaultRoute = 'job';
        $this->client = new JobClient(['addr'=>$this->addr]);
    }
}