<?php
namespace kaikaige\job\controllers;

use kaikaige\job\components\JobClient;

class Controller extends \yii\web\Controller
{
    /**
     * @var JobClient
     */
    public $jobClient;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->jobClient = $this->module->client;
        $this->layout = '../layouts/main';
    }
}