<?php

namespace kaikaige\job\components;

use yii\base\Component;
use yii\db\Exception;
use yii\httpclient\Client;
use yii\httpclient\Response;

class JobClient extends Component
{
    /**
     * @var string dq连接地址
     */
    public $addr;

    /**
     * @var Client
     */
    public $httpClient;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (!$this->addr) {
            throw new \Exception("property addr 不能为空");
        }
        $this->httpClient = new Client(['baseUrl' => $this->addr]);
    }

    public function jobList()
    {
        $res = $this->httpClient->get('task')->send()->getData();
        if ($res['code'] != 0) {
            throw new \Exception($res['message']);
        }
        return $res['data'];
    }

    public function jobCreate($data)
    {
        return $this->httpClient->post('task/store', $data)->send()->getData();
    }

    public function hostList()
    {
        $this->httpClient->get('host/all')->send()->getData();
        if ($res['code'] != 0) {
            throw new \Exception($res['message']);
        }
        return $res['data'];
    }

    public function hostCreate($data)
    {
        return $this->httpClient->post('host/store', $data)->send()->getData();
    }

    public function hostTest($host_id)
    {
        return $this->httpClient->post('host/ping/'.$host_id)->send()->getData();
    }

    public function hostDelete($host_id)
    {
        return $this->httpClient->post('host/remove/'.$host_id)->send()->getData();
    }
}


